apiVersion: v1
kind: Service
metadata:
  name: web01-svc
spec:
  type: LoadBalancer
  selector:
    app: web01
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web01-deployment
spec:
  selector:
    matchLabels:
      app: web01
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web01
    spec:
      containers:
      - name: php
        image: php:latest
        ports:
        - containerPort: 80
